Add Pipeline
scVENUS/PeekabooAV-Installer pull request #75
Opened 2022-03-15 09:53 UTC by Sett17

This adds a showcase pipeline using docker and docker-compose.

This modifies the PeekabooAV Dockerfile, to result in a smaller image than before.

And then adds other services needed for a fully functional email pipeline with an antivirus system, including:
- Postfix containers (one acting as a 'sender' and one as a 'receiver')
- rspamd as the spam filtering system, and
- Cortex for Analysis of Observables (+plus a container to automatically set it up)

2022-03-15 14:39 UTC, michaelweiser requested changes
@sett17 : This is some seriously awesome stuff. Thanks for working on this! In this first round of review I have mostly nits and procedural requests and suggestions. Otherwise this looks really good!

2022-03-15 14:39 UTC, michaelweiser commented on peekaboo/peekaboo.conf
> + host             :    0.0.0.0
Huh, that would change the ansible installer behaviour as well and make our socket available to the world without authentication when installed on a bare-metal or virtual machine! Let's employ our entrypoint here for dynamic configuration. See https://github.com/michaelweiser/PeekabooAV-Installer/commit/a26b88a708828914843e21cbce34d115c49edc7b

2022-03-15 14:39 UTC, michaelweiser commented on compose.yaml
> +      - ./pipeline/data/elastic:/usr/share/elasticsearch/data ##VOLUME
What's the purpose of the `##VOLUME` comment?

2022-03-15 14:39 UTC, michaelweiser commented on compose.yaml
>        timeout: 30s
commit comment nit: contains a sc_r_ipt,

2022-03-15 14:39 UTC, michaelweiser commented on cortex_setup/cortexSetup.sh
> + echo "must specify a URL with -cu / --cortex-url (without path or trailing /, e.g. http://cortex:9001)"
Inconsistent indent: If it has to be spaces, we should make it consistently be two or four. I'd prefer tabs though but that's just my taste.

2022-03-15 16:12 UTC, Sett17 commented on compose.yaml
> +      - ./pipeline/data/elastic:/usr/share/elasticsearch/data ##VOLUME
The `##VOLUME` occurrences are referenced in the compose.env comment.
Rethinking it, there is no need to indicate these 'hard-coded' volumes since they are not supposed to be changed anyway.

2022-03-16 07:31 UTC, michaelweiser requested changes
Much improvements, some more minor nits.

2022-03-16 07:31 UTC, michaelweiser commented on Dockerfile
> +FROM debian:bullseye-slim AS build
first one seems fixed, other two remain

2022-03-16 07:31 UTC, michaelweiser commented on Dockerfile
>  USER peekaboo
Added as separate commit. Can we squash them? (BTW: I have no interest in any credit. Just squash and add a note. I intentionally kept the commit messages brief because I expected squashing.)

2022-03-16 07:31 UTC, michaelweiser commented on peekaboo/peekaboo.conf
> + host             :    0.0.0.0
Here we'd need to restore the original value of `127.0.0.1` as well when squashing the dynamic config commit to keep the diff to the sample PeekabooAV config minimal.

2022-03-16 07:31 UTC, michaelweiser commented on .dockerignore
> +pipeline/data/
done.

2022-03-16 07:31 UTC, michaelweiser commented on compose.yaml
> +      - "9001:9001"
Can be squashed as well.

2022-03-16 07:31 UTC, michaelweiser commented on compose.yaml
>        timeout: 30s
done.

2022-03-16 07:31 UTC, michaelweiser commented on Vagrantfile
>  Vagrant.configure("2") do |config|
There's something funky going on here with the rebase. Commits from #74 show up as new here. Can you rebase again to current master?

2022-03-16 07:31 UTC, michaelweiser commented on compose.yaml
>    rspamd:
Can you squash this commit into "[rspamd: Added rspamd container and needed File](https://github.com/scVENUS/PeekabooAV-Installer/pull/75/commits/8842dfba20c43b25c63ed86f0f90124ebb3a2428)"? I think this ties it all together and IIRC makes it work (particularly enabling `external_services` and `force_actions`).

Also (cannot resist, sorry) commit comment nit for the latter commit: needed _f_ile (lower case), and con_f_igures rspamd

2022-03-16 08:28 UTC, Sett17 commented on Dockerfile
> +FROM debian:bullseye-slim AS build
Could you be more specific about the second requested change, "application start no , is moved"?

2022-03-16 09:02 UTC, michaelweiser commented on Dockerfile
> +FROM debian:bullseye-slim AS build
I'm referreing to the redundant comma in the commit message after application start.

2022-03-16 11:09 UTC, michaelweiser approved these changes
LVGTM ;)

2022-03-16 11:10 UTC, michaelweiser commented on Vagrantfile
>  Vagrant.configure("2") do |config|
resolved.

2022-03-16 11:10 UTC, michaelweiser commented on compose.yaml
> +      - "9001:9001"
done.

2022-03-16 11:11 UTC, michaelweiser commented on peekaboo/peekaboo.conf
> + host             :    0.0.0.0
done.

2022-03-16 11:12 UTC, michaelweiser commented on compose.yaml
> +      - ./pipeline/data/elastic:/usr/share/elasticsearch/data ##VOLUME
agreed.

2022-03-16 11:12 UTC, michaelweiser commented on compose.yaml
> +      - type: bind # This has to be bind mount, because the shorthand creates a directory on the target instead of a file (shorthand words if the file is already present in th target)
done.

2022-03-23 12:19 UTC, Jack28 approved these changes
LGTM

2022-03-23 12:19 UTC, merged

2022-03-23 13:05 UTC, michaelweiser commented
@sett17 : Thanks again for your great work on this! Feel free to jump into the discussion on #76 as well.